MineSweeper/Controllers/GameBoardController.cs
using Microsoft.AspNetCore.Mvc;
using MineSweeper.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;



/**
 * NOTES
 * Formula to turn row and col into an ID number
 * row * size + col
 * ex. (2 * 8) + 3
 * to turn an ID into a row and col 
 * use ID/ size to get the row
 * use ID % size to get the column number
 */

namespace MineSweeper.Controllers
{
    public class GameBoardController : Controller
    {

        public static BoardModel board;

        double difficulity = 0.00;
        int size;


        public IActionResult PageSetup(string boardSize, string gameDiff)
        {
            size = Convert.ToInt32(boardSize);
            difficulity = Convert.ToDouble(gameDiff);
            board = new BoardModel(size, difficulity);
            return Index();
        }

        public IActionResult Index()
        {
            return View("Index", board);
        }





        public IActionResult HandleButtonClick(int row, int col)
        {
           
            //calls board.leftClick and checks for flag
            PlaceTurn(row, col);

            //check for end-game contitions
            if (board.checkForLose())
            {
                board.revealBombs();

                return PartialView("GameLost", board);
            }
            else if (board.checkForWin())
            {
                //not real view name
                return GameWon();
            }
            return PartialView("ShowOneButton", board);
        }


        public IActionResult ShowOneButton()
        {

            return PartialView("ShowOneButton", board);
        }

        public IActionResult RightClickShowButton(int row, int col)
        {
            flagSwap(row, col);

            return PartialView("ShowOneButton", board);
        }

        public void flagSwap(int row, int col)
        {

            if (board.Grid[row, col].flag == false)
            {
                board.Grid[row, col].flag = true;
                board.Grid[row, col].enabled = false;
                board.Grid[row, col].visited = true;
            }
            else
            {
                board.Grid[row, col].flag = false;
                board.Grid[row, col].enabled = true;
                board.Grid[row, col].visited = false;
            }
        }



        public void PlaceTurn(int rowNumber, int columnNumber)
        {
            //used for testing
            Console.WriteLine(rowNumber + " " + columnNumber);


            if (board.Grid[rowNumber, columnNumber].enabled == true)
            {
                board.Grid[rowNumber, columnNumber].visited = true;
            }
            // update board.  false = update only one square.
            board.leftClick(rowNumber, columnNumber);

        }







        public IActionResult GameWon()
        {

            return PartialView("GameWon", board);

        }

        public IActionResult GameLost()
        {
            return PartialView("GameLost", board);
        }
    }
}

MineSweeper/Controllers/SaveController.cs
using Microsoft.AspNetCore.Mvc;
using MineSweeper.Models;
using MineSweeper.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Http.Description;

namespace MineSweeper.Controllers
{

    //[ApiController]
    //[Route("api/[controller]")]

    public class SaveController : Controller
    {
        SaveDAO saveGame = new SaveDAO();

        //[HttpPut("processSave")]
        public IActionResult ProcessSave()
        {
            if(saveGame.createSave(GameBoardController.board, "ThatGhostToast"))
            {
                return PartialView("SaveCreated");

            } else
            {
                return PartialView("SaveFailed");
            }
        }

        //[HttpGet("getSavedBoard")]
        //[ResponseType(typeof(BoardModel))]

        public ActionResult<List<BoardModel>> GetSavedBoard(string username)
        {
            List<BoardModel> boards = saveGame.getSavedBoard(username);

            return boards;
       
        }

    }
}

MineSweeper/Views/GameBoard/GameLost.cshtml
@model MineSweeper.Models.BoardModel

    <style>
        

        .bodyTxt {
            text-align: center;
        }
    </style>



<div class="bodyTxt">
    <h1> You Lost! Loser!!</h1>
    <h2>Click the link below to start a new game!</h2>

    <a asp-controller="boardsetup" asp-action="Index">Game Board</a>

</div>
<style>
    .game-button {
        width: 74px;
        height: 74px;
        text-align: center;
        background-color: gray;
        color: white;
    }

    .game-button-image {
        width: 70%;
    }

    .button-zone {
        display: flex;
        flex-wrap: wrap;
    }

    .line-break {
        flex-basis: 100%;
        height: 0;
    }
</style>

<br />



<form id="button-grid">
    <div class="button-zone">

        @for (int b = 0; b < Model.size; b++)
        {
            @for (int c = 0; c < Model.size; c++)
            {



                <div class="OneButton" id="@b">
                    <!-- while the game is still running-->
                  

                        @if (Model.Grid[b, c].visited == false)
                        {
                            <button class="game-button" name="buttonId" id="@b" value="@Model.Grid[b, c].row @Model.Grid[b, c].column" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                                ?
                            </button>
                        }
                        else if (@Model.Grid[b, c].liveNeighbors > 0 && @Model.Grid[b, c].live == false && @Model.Grid[b, c].visited == true)
                        {
                            <button class="game-button" name="buttonId" id="gameButton" value="@Model.Grid[b, c].row @Model.Grid[b, c].column" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                                @Model.Grid[b, c].liveNeighbors
                            </button>
                        }
                        else if (Model.Grid[b, c].flag == true)
                        {
                            <button class="game-button" name="buttonId" id="@b" value="@Model.Grid[b, c].row @Model.Grid[b, c].column" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                                <img class="game-button-image" src="~/img/Flag.png" />
                            </button>

                            Model.Grid[b, c].enabled = false;
                        }
                        else if (@Model.Grid[b, c].live == false && @Model.Grid[b, c].liveNeighbors == 0 && @Model.Grid[b, c].visited == true)
                        {
                            <button class="game-button" name="buttonId" id="@b" value="@Model.Grid[b, c].row @Model.Grid[b, c].column" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                            </button>
                        }
                        else if (Model.Grid[b, c].live == true)
                        {
                            <button class="game-button" name="buttonId" id="@b" value="@Model.Grid[b, c].row @Model.Grid[b, c].column" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                                <img class="game-button-image" src="~/img/bomb.png" alt="bomb" />
                            </button>
                        }


                    

                    
                </div>

            }
            <div class="line-break"></div>
        }

    </div>
</form>

MineSweeper/Views/GameBoard/GameWon.cshtml
@model MineSweeper.Models.BoardModel


<style>


    .bodyTxt {
        text-align: center;
    }
</style>



<div class="bodyTxt">
    <h1> You won! Congradulations!</h1>
    <h2>Click the link below to start a new game!</h2>


    <a asp-controller="boardsetup" asp-action="Index">Game Board</a>

</div>
<style>
    .game-button {
        width: 74px;
        height: 74px;
        text-align: center;
        background-color: gray;
        color: white;
    }

    .game-button-image {
        width: 70%;
    }

    .button-zone {
        display: flex;
        flex-wrap: wrap;
    }

    .line-break {
        flex-basis: 100%;
        height: 0;
    }
</style>

<br />



<form id="button-grid">
    <div class="button-zone">

        @for (int b = 0; b < Model.size; b++)
        {
            @for (int c = 0; c < Model.size; c++)
            {



                <div class="OneButton" id="@b">
                    <!-- while the game is still running-->


                    @if (Model.Grid[b, c].visited == false)
                    {
                        <button class="game-button" name="buttonId" id="@b" value="@Model.Grid[b, c].row @Model.Grid[b, c].column" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                            ?
                        </button>
                    }
                    else if (@Model.Grid[b, c].liveNeighbors > 0 && @Model.Grid[b, c].live == false && @Model.Grid[b, c].visited == true)
                    {
                        <button class="game-button" name="buttonId" id="gameButton" value="@Model.Grid[b, c].row @Model.Grid[b, c].column" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                            @Model.Grid[b, c].liveNeighbors
                        </button>
                    }
                    else if (Model.Grid[b, c].flag == true)
                    {
                        <button class="game-button" name="buttonId" id="@b" value="@Model.Grid[b, c].row @Model.Grid[b, c].column" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                            <img class="game-button-image" src="~/img/Flag.png" />
                        </button>

                        Model.Grid[b, c].enabled = false;
                    }
                    else if (@Model.Grid[b, c].live == false && @Model.Grid[b, c].liveNeighbors == 0 && @Model.Grid[b, c].visited == true)
                    {
                        <button class="game-button" name="buttonId" id="@b" value="@Model.Grid[b, c].row @Model.Grid[b, c].column" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                        </button>
                    }
                    else if (Model.Grid[b, c].live == true)
                    {
                        <button class="game-button" name="buttonId" id="@b" value="@Model.Grid[b, c].row @Model.Grid[b, c].column" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                            <img class="game-button-image" src="~/img/bomb.png" alt="bomb" />
                        </button>
                    }





                </div>

            }
            <div class="line-break"></div>
        }

    </div>
</form>

MineSweeper/Views/GameBoard/Index.cshtml
@model MineSweeper.Models.BoardModel


<p>The current time is @DateTime.Now in index page</p>
<style>
    .game-button {
        width: 74px;
        height: 74px;
        text-align: center;
        background-color: gray;
        color: white;
    }

    .game-button-image {
        width: 70%;
    }

    .button-zone {
        display: flex;
        flex-wrap: wrap;
    }

    .line-break {
        flex-basis: 100%;
        height: 0;
    }
</style>

<br />

<form id="button-grid">
    <div class="button-zone" id="button-zone">

        @for (int b = 0; b < Model.size; b++)
        {
            @for (int c = 0; c < Model.size; c++)
            {

        <div class="OneButton" id="@b">
            <!-- while the game is still running-->
            @if (@Model.Grid[b, c].enabled == true)
            {

                @if (@Model.Grid[b, c].visited == false)
                {
                    <button class="game-button" name="buttonId" id="@b" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                        ?
                    </button>
                }
                else if (Model.Grid[b, c].flag == true)
                {
                    <button class="game-button" name="buttonId" id="@b" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                        <img class="game-button-image" src="~/img/Flag.png" />
                    </button>

                    Model.Grid[b, c].enabled = false;
                }
                else if (@Model.Grid[b, c].liveNeighbors > 0 && @Model.Grid[b, c].live == false && @Model.Grid[b, c].visited == true)
                {
                    <button class="game-button" name="buttonId" id="gameButton" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                        @Model.Grid[b, c].liveNeighbors
                    </button>
                }

                else if (@Model.Grid[b, c].live == false && @Model.Grid[b, c].liveNeighbors == 0 && @Model.Grid[b, c].visited == true)
                {
                    <button class="game-button" name="buttonId" id="@b" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                    </button>
                }
                else if (Model.Grid[b, c].live == true)
                {
                    <button class="game-button" name="buttonId" id="@b" value="@b @c" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                        <img class="game-button-image" src="~/img/bomb.png" alt="bomb" />
                    </button>
                }


            }

            else
            {
                @if (@Model.Grid[b, c].visited == false)
                {
                    <button class="game-button" name="buttonId" id="@b" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                        ?
                    </button>
                }
                else if (Model.Grid[b, c].flag == true && Model.Grid[b, c].visited == true)
                {
                    <button class="game-button" name="buttonId" id="@b" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                        <img class="game-button-image" src="~/img/Flag.png" />
                    </button>

                    Model.Grid[b, c].enabled = false;
                }
                else if (@Model.Grid[b, c].liveNeighbors > 0 && @Model.Grid[b, c].live == false && @Model.Grid[b, c].visited == true)
                {
                    <button class="game-button" name="buttonId" id="@b" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                        @Model.Grid[b, c].liveNeighbors
                    </button>
                }

                else if (@Model.Grid[b, c].live == false && @Model.Grid[b, c].liveNeighbors == 0 && @Model.Grid[b, c].visited == true)
                {
                    <button class="game-button" name="buttonId" id="@b" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                    </button>
                }
                else if (Model.Grid[b, c].live == true)
                {
                    <button class="game-button" name="buttonId" id="gameButton" value="@b @c" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                        <img class="game-button-image" src="~/img/bomb.png" alt="bomb" />
                    </button>
                }
            }
        </div>

            }
            <div class="line-break"></div>
        }


    </div>
</form>

<br />

<input type="button" value="save" onclick="location.href = '@Url.Action("ProcessSave", "Save")'" />

MineSweeper/Views/GameBoard/ShowOneButton.cshtml
@model MineSweeper.Models.BoardModel




<p>The current time is @DateTime.Now</p>


<div class="line-break"></div>


@for (int b = 0; b < Model.size; b++)
{
    @for (int c = 0; c < Model.size; c++)
    {


<div class="OneButton" id="@b">
    <!-- while the game is still running-->
    @if (@Model.Grid[b, c].enabled == true)
    {

        @if (@Model.Grid[b, c].visited == false)
        {
            <button class="game-button" name="buttonId" id="@b" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                ?
            </button>
        }

        else if (Model.Grid[b, c].flag == true)
        {
            <button class="game-button" name="buttonId" id="@b" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                <img class="game-button-image" src="~/img/Flag.png" />
            </button>

            Model.Grid[b, c].enabled = false;
        }
        else if (@Model.Grid[b, c].liveNeighbors > 0 && @Model.Grid[b, c].live == false && @Model.Grid[b, c].visited == true)
        {
            <button class="game-button" name="buttonId" id="gameButton" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                @Model.Grid[b, c].liveNeighbors
            </button>
        }
        else if (@Model.Grid[b, c].live == false && @Model.Grid[b, c].liveNeighbors == 0 && @Model.Grid[b, c].visited == true)
        {
            <button class="game-button" name="buttonId" id="@b" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
            </button>
        }
        else if (Model.Grid[b, c].live == true)
        {
            <button class="game-button" name="buttonId" id="@b" value="@b @c" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                <img class="game-button-image" src="~/img/bomb.png" alt="bomb" />
            </button>
        }


    }

    else
    {
        @if (@Model.Grid[b, c].visited == false)
        {
            <button class="game-button" name="buttonId" id="@b" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                ?
            </button>
        }

        else if (Model.Grid[b, c].flag == true && Model.Grid[b, c].visited == true)
        {
            <button class="game-button" name="buttonId" id="@b" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                <img class="game-button-image" src="~/img/Flag.png" />
            </button>

            Model.Grid[b, c].enabled = false;
        }
        else if (@Model.Grid[b, c].live == false && @Model.Grid[b, c].liveNeighbors == 0 && @Model.Grid[b, c].visited == true)
        {
            <button class="game-button" name="buttonId" id="@b" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
            </button>
        }
        else if (@Model.Grid[b, c].liveNeighbors > 0 && @Model.Grid[b, c].live == false && @Model.Grid[b, c].visited == true)
        {
            <button class="game-button" name="buttonId" id="@b" value="@b @c" type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                @Model.Grid[b, c].liveNeighbors
            </button>
        }
        else if (Model.Grid[b, c].live == true)
        {
            <button class="game-button" name="buttonId" id="gameButton" value="@b @c" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                <img class="game-button-image" src="~/img/bomb.png" alt="bomb" />
            </button>
        }
    }
</div>

    }
<div class="line-break"></div>
}

MineSweeper/Views/GameBoard/gameWon.cshtml
@model MineSweeper.Models.BoardModel


<style>


    .bodyTxt {
        text-align: center;
    }
</style>



<div class="bodyTxt">
    <h1> You won! Congradulations!</h1>
    <h2>Click the link below to start a new game!</h2>


    <a asp-controller="boardsetup" asp-action="Index">Game Board</a>

</div>
<style>
    .game-button {
        width: 74px;
        height: 74px;
        text-align: center;
        background-color: gray;
        color: white;
    }

    .game-button-image {
        width: 70%;
    }

    .button-zone {
        display: flex;
        flex-wrap: wrap;
    }

    .line-break {
        flex-basis: 100%;
        height: 0;
    }
</style>

<br />



<form id="button-grid">
    <div class="button-zone">

        @for (int b = 0; b < Model.size; b++)
        {
            @for (int c = 0; c < Model.size; c++)
            {



                <div class="OneButton" id="@b">
                    <!-- while the game is still running-->


                    @if (Model.Grid[b, c].visited == false)
                    {
                        <button class="game-button" name="buttonId" id="@b" value="@Model.Grid[b, c].row @Model.Grid[b, c].column" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                            ?
                        </button>
                    }
                    else if (@Model.Grid[b, c].liveNeighbors > 0 && @Model.Grid[b, c].live == false && @Model.Grid[b, c].visited == true)
                    {
                        <button class="game-button" name="buttonId" id="gameButton" value="@Model.Grid[b, c].row @Model.Grid[b, c].column" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                            @Model.Grid[b, c].liveNeighbors
                        </button>
                    }
                    else if (Model.Grid[b, c].flag == true)
                    {
                        <button class="game-button" name="buttonId" id="@b" value="@Model.Grid[b, c].row @Model.Grid[b, c].column" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                            <img class="game-button-image" src="~/img/Flag.png" />
                        </button>

                        Model.Grid[b, c].enabled = false;
                    }
                    else if (@Model.Grid[b, c].live == false && @Model.Grid[b, c].liveNeighbors == 0 && @Model.Grid[b, c].visited == true)
                    {
                        <button class="game-button" name="buttonId" id="@b" value="@Model.Grid[b, c].row @Model.Grid[b, c].column" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                        </button>
                    }
                    else if (Model.Grid[b, c].live == true)
                    {
                        <button class="game-button" name="buttonId" id="@b" value="@Model.Grid[b, c].row @Model.Grid[b, c].column" disabled type="submit" asp-controller="GameBoard" asp-action="HandleButtonClick">
                            <img class="game-button-image" src="~/img/bomb.png" alt="bomb" />
                        </button>
                    }





                </div>

            }
            <div class="line-break"></div>
        }

    </div>
</form>